
const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST"
const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS"
const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE"

export {GET_LOGIN_REQUEST ,GET_LOGIN_SUCCESS , GET_LOGIN_FAILURE } 