
const GET_MUSIC_RECORD_REQUEST = "GET_MUSIC_RECORD_REQUEST" ;
const GET_MUSIC_RECORD_SUCCESS = "GET_MUSIC_RECORD_SUCCESS" ;
const GET_MUSIC_RECORD_FAILURE = "GET_MUSIC_RECORD_FAILURE" ;
 
export {GET_MUSIC_RECORD_REQUEST , GET_MUSIC_RECORD_FAILURE ,GET_MUSIC_RECORD_SUCCESS}